### ISSUE TITLE
Tensorflow error while the container running

### ISSUE THREAD

**Issue by laleye** [BaderLab/Saber#199]
I got this error when I tried to run the docker container. May be That comes from the tensorflow version in the dockerfile?

Using TensorFlow backend.
Saber version: 0.1.0-alpha
Loading model... Downloading 13s9wvu3Mc8fG73w51KD8RArA31vsuL1c into /app/saber/pretrained_models/CHED.tar.bz2... Done.
Unzipping... Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/saber/cli/app.py", line 93, in <module>
    MODELS, GRAPH = app_utils.load_models(constants.ENTITIES)
  File "/app/saber/utils/app_utils.py", line 109, in load_models
    saber.load(ent)
  File "/app/saber/saber.py", line 215, in load
    model_filepath=model_filepath)
  File "/app/saber/utils/model_utils.py", line 230, in load_pretrained_model
    model.load(weights_filepath, model_filepath)
  File "/app/saber/models/multi_task_lstm_crf.py", line 52, in load
    model = model_from_json(f.read(), custom_objects={'CRF': CRF})
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1109, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by JohnGiorgi** [comment]
Hi @laleye,

We are no longer maintaining this code. Please let me know if you need to evaluate the model for a paper comparison and I will try to help you out.
